config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'user_files#index'
  resources :user_files
  get 'user_files/download/:id', to: 'user_files#download'
  get 'admin/all_files', to: 'admin#all_files'
  get 'admin/clean_cache', to: 'admin#clean_cache'
  resources :admin, only: [:index, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_files
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def fio
    "#{self.try(:last_name)} #{self.try(:first_name)} #{self.try(:middle_name)}"
  end
end

app/models/user_file.rb
class UserFile < ApplicationRecord
    belongs_to :user
    mount_uploader :file_image, FileImageUploader
    def is_video
        self.file_type.include?('video')
    end
    def is_pdf
        self.file_type.include?('pdf')
    end
    def is_image
        self.file_type.include?('image')
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    before_action :is_admin

    before_action :set_user, only:[:edit, :update, :destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end
    
    def edit
        render 'admin/new'
    end

    def destroy
        @user.destroy
        redirect_to action: "index"
    end

    def update
        @user.attributes = user_params
        @user.save(validate: !user_params[:password].blank?)
        redirect_to action: "index"
    end

    def create
        @user = User.new(user_params)
        @user.save
        redirect_to action: "index"
    end

    def all_files
        @user_files = UserFile.all
        puts params
        render 'user_files/index'
    end

    def clean_cache
        remove_dir("#{Rails.root}/public/#{FileImageUploader.cache_dir}") if File.exist?("#{Rails.root}/public/#{FileImageUploader.cache_dir}")
    end

    private
    def remove_dir(path)
        if File.directory?(path)
          Dir.foreach(path) do |file|
            if ((file.to_s != ".") and (file.to_s != ".."))
              remove_dir("#{path}/#{file}")
            end
          end
          Dir.delete(path)
        else
          File.delete(path)
        end
    end
      

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :middle_name, :birth_date, :email, :password)
    end

    def service_parameters
        %s[utf8 authenticity_token commit controller action]
    end

    def is_admin
        redirect_back(fallback_location: root_path) unless current_user.is_super_user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :first_name, :last_name, :middle_name, :birth_date)}
        end
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
  before_action :set_user_file, only: [:show, :edit, :update, :destroy]
  before_action :cache_user_file, only: [:show]
  before_action :clean_cache_user_file, only: [:index]
  # GET /user_files or /user_files.json
  def index
    @user_files = current_user.user_files
  end

  # GET /user_files/1 or /user_files/1.json
  def show
  end

  # GET /user_files/new
  def new
    @user_file = UserFile.new
  end

  # GET /user_files/1/edit
  def edit
  end

  # POST /user_files or /user_files.json
  def create
    return unless params[:user_file][:file_image]
    
    @user_file = UserFile.new(user_file_params)

    respond_to do |format|
      if @user_file.save
        format.html { redirect_to user_file_url(@user_file), notice: "User file was successfully created." }
        format.json { render :show, status: :created, location: @user_file }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_files/1 or /user_files/1.json
  def update
    return unless params[:user_file][:file_image]

    respond_to do |format|
      if @user_file.update(user_file_params)
        format.html { redirect_to user_file_url(@user_file), notice: "User file was successfully updated." }
        format.json { render :show, status: :ok, location: @user_file }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_files/1 or /user_files/1.json
  def destroy
    @user_file.destroy

    respond_to do |format|
      format.html { redirect_to user_files_url, notice: "User file was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_file
      @user_file = UserFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_file_params
      {
        user_id: params[:user_file][:user_id],
        file_image: params[:user_file][:file_image],
        file_name: params[:user_file][:file_image].original_filename,
        file_type: params[:user_file][:file_image].content_type,
        file_size: params[:user_file][:file_image].size
      }
    end

    def cache_user_file
      @user_file.file_image.cache!
    end

    def clean_cache_user_file
      File.delete(@user_file.file_image.cache_path) if @user_file
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/views/admin/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Пользователи</h1>

<table>
  <thead>
    <tr>
      <th>Фамилия</th>
      <th>Имя</th>
      <th>Отчество</th>
      <th>Дата рождения</th>
      <th>Адрес электронной почты</th>
      <th>Дата регистрации</th>
      <th>Дата последнего изменения</th>
      <th>Это суперпользователь?</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.middle_name %></td>
        <td><%= user.birth_date %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.is_super_user %></td>
        <td><%= link_to 'Изенить пользователя', "/admin/#{ user.id }/edit" %></td>
        <td><%= link_to 'Удалить пользователя', "/admin/#{ user.id }", method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Зарегистрировать нового пользователя", '/admin/new' %>

app/views/admin/new.html.erb
<%
case params[:action]
when 'new'
  method = :post
  url = '/admin'
  header = 'Регистрация'
  submit = 'Зарегистрировать пользователя'
when 'edit'
  method = :put
  url = "/admin/#{@user.id}"
  header = "Изенение пользователя #{@user.fio}"
  submit = 'Изменить параметры пользователя'
end
%>

<h2><%= header %></h2>

<%= form_with(model: @user, url: url, method: method) do |f| %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "Фамилия" %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "Имя" %>
  </div>

  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name, autofocus: true, autocomplete: "Отчетсво" %>
  </div>

  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.date_field :birth_date, autofocus: true, autocomplete: "Дата рожденяи" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "Адрес электронной почты" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloudArchive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <ul>
        <li><p><%= current_user.fio %></p></li>
        <li><p><%= link_to 'Ваше хранилище', '/' if current_user.is_super_user %></p></li>
        <li><p><%= link_to 'Список пользователей', :admin_index if current_user.is_super_user %></p></li>
        <li><p><%= link_to  'Список всех фалов системы', :admin_all_files if current_user.is_super_user %></p></li>
        <li><p><%= link_to  'Отчистить кэш', '#', id: 'clean_cache_btn', onclick: 'send_clean_cache()' if current_user.is_super_user %></p></li>
        <li style="float:right"><p><%= link_to "Выход", destroy_user_session_path, :method => :delete %></p></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/user_files/_form.html.erb
<%= form_with(model: user_file) do |form| %>
  <% if user_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_file.errors.count, "error") %> prohibited this user_file from being saved:</h2>

      <ul>
      <% user_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Выбрать файл для отправки:</label><br />
    <%= form.file_field :file_image %><br />
  </div>

  <div>
    <%= form.submit 'Загрузить файл в систему' %>
  </div>

  <%= form.hidden_field :user_id, {value: current_user.id} %>
<% end %>

app/views/user_files/edit.html.erb
<h1>Editing User File</h1>

<%= render 'form', user_file: @user_file %>

<%= link_to 'Показать', @user_file %> |
<%= link_to 'Вернуться', user_files_path %>

app/views/user_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Доступные файлы</h1>

<table>
  <thead>
    <tr>
      <th>Название файла</th>
      <th>Тип</th>
      <th>Размерт в битах</th>
      <% if params[:action] == "all_files" %>
        <th>ФИО владельца</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_files.each do |user_file| %>
      <tr>
        <td><%= user_file.file_name %></td>
        <td><%= user_file.file_type %></td>
        <td><%= user_file.file_size %> </td>
        <% if params[:action] == "all_files" %>
          <td><%= user_file.user.fio %> </td>
        <% end %>
        <td><%= link_to 'Просомтерть файл', user_file %></td>
        <td><%= link_to 'Удалить файл', user_file, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% unless params[:action] == "all_files" %>
  <%= link_to 'Добавить файл', new_user_file_path %>
<% end %>

app/views/user_files/new.html.erb
<h1>Отправка фйла</h1>

<%= render 'form', user_file: @user_file %><br />

<%= link_to 'Вернуться', user_files_path %>

app/views/user_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя:</strong>
  <%= @user_file.file_name %>
</p>

<p>
  <strong>Тип:</strong>
  <%= @user_file.file_type %>
</p>

<p>
  <strong>Размер:</strong>
  <%= @user_file.file_size %>
</p>

<p>
  <strong>Визуальное представление фалйа:</strong>
</p>

<p>
  <%= image_tag(@user_file.file_image.url, alt: 'Image') if @user_file.file_image? && @user_file.is_image%>
  <% if @user_file.file_image? && @user_file.is_video %>
    <video controls="" name="media"><source src=<%= @user_file.file_image.url %> type="video/mp4"></video>
  <% end %>
  <% if @user_file.file_image? && @user_file.is_pdf %>
    <iframe src=<%= @user_file.file_image.url %> width="800" height="1000" style="border: none;"> </iframe>
  <% end %>
</p>

<p>
  <a href=<%= @user_file.file_image.url %> download>Скачать</a>
</p>

<%= link_to 'Вернуться', user_files_path %>